name: Dependency check

on:
  push:
    branches: [main, feature/*]
  schedule:
    - cron: "5 4 * * 0"

jobs:
  outdated:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/

      - uses: pnpm/action-setup@v3
        with:
          version: latest

      - run: pnpm i
      - run: echo **WORD FREQUENCY** > outdated
      - run: pnpm outdated --format json >> outdated
      - name: send telegram message on push
        if: always()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message_file: outdated
